-- ============================================================================
-- DDL PROPIETARIO EXCLUSIVO DE orders-service
-- ============================================================================
-- Esta base de datos contiene ÚNICAMENTE las tablas que Orders posee:
--   orders, order_items, client
--
-- Referencias a otras tablas NO existen como FOREIGN KEY:
--   orders.restaurant_id   -> Catalog  (restaurant.id)   [ref externa Long]
--   orders.delivery_id     -> Delivery (delivery.id)     [ref externa Long]
--   order_items.product_id -> Catalog  (products.id)     [ref externa Long]
--   client.user_id         -> Auth     (users.id)        [ref externa Long]
--
-- Esas relaciones se resuelven por HTTP interno (ver TEAM_INTERNAL_API_CONTRACTS.md C-1..C-7),
-- jamás mediante joins/queries SQL entre bases de datos.
--
-- Las claves propias (orders.id, order_items.id, client.id) son BIGINT y se exponen
-- como UUID en el dominio a través de IdConverter (UUID <-> Long).
-- ============================================================================

-- 1) client (propiedad de Orders). user_id es referencia externa a Auth (sin FK).
CREATE TABLE IF NOT EXISTS public.client (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    bigint NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now(),
  end_date   timestamptz
);

-- 2) orders (propiedad de Orders). client_id FK interna; restaurant_id/delivery_id refs externas.
CREATE TABLE IF NOT EXISTS public.orders (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id      bigint NOT NULL,
  restaurant_id  bigint NOT NULL,
  delivery_id    bigint,
  status         text NOT NULL DEFAULT 'Nuevo pedido',
  address        text NOT NULL,
  subtotal       numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  delivery_fee   numeric(12,2) NOT NULL DEFAULT 0 CHECK (delivery_fee >= 0),
  total          numeric(12,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
  payment_method text NOT NULL DEFAULT 'Efectivo',
  created_at     timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_orders_client FOREIGN KEY (client_id) REFERENCES public.client(id) ON DELETE RESTRICT
);

-- 3) order_items (propiedad de Orders). order_id FK interna; product_id ref externa.
CREATE TABLE IF NOT EXISTS public.order_items (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   bigint NOT NULL,
  product_id bigint NOT NULL,
  quantity   integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price numeric(12,2) NOT NULL CHECK (unit_price >= 0),
  total      numeric(12,2) NOT NULL CHECK (total >= 0),
  CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE
);

-- Índices justificados por las queries reales de orders-service:
CREATE INDEX IF NOT EXISTS idx_orders_client        ON public.orders(client_id);
CREATE INDEX IF NOT EXISTS idx_orders_restaurant    ON public.orders(restaurant_id);
CREATE INDEX IF NOT EXISTS idx_orders_delivery      ON public.orders(delivery_id);
-- countActiveOrdersByDelivery filtra por delivery_id + status IN (En camino, Retirado)
CREATE INDEX IF NOT EXISTS idx_orders_delivery_status ON public.orders(delivery_id, status);
CREATE INDEX IF NOT EXISTS idx_order_items_order    ON public.order_items(order_id);
-- client(user_id) está cubierto por la UNIQUE; no se crea índice adicional.
-- idx_order_items_product NO se crea: Orders nunca filtra order_items por product_id.
