create table public.categories (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    description varchar(255),
    image varchar(255),
    created_at timestamp(6) not null default current_timestamp
);

create table public.restaurant (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique,
    name varchar(255) not null,
    address varchar(255),
    created_at timestamp(6) not null default current_timestamp
);

create table public.products (
    id bigint generated by default as identity primary key,
    category_id bigint not null references public.categories(id) on delete restrict,
    restaurant_id bigint not null references public.restaurant(id) on delete cascade,
    name varchar(255) not null,
    description varchar(255),
    price numeric(12,2) not null check (price >= 0),
    image varchar(255),
    is_available boolean not null default true,
    created_at timestamp(6) not null default current_timestamp
);

create index idx_products_category_id on public.products(category_id);
create index idx_products_restaurant_id on public.products(restaurant_id);
create index idx_products_is_available on public.products(is_available);
create index idx_restaurant_user_id on public.restaurant(user_id);