create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  image text,
  created_at timestamptz not null default now()
);

create table if not exists public.restaurant (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique,
  name text not null,
  address text,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  restaurant_id bigint not null references public.restaurant(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  image text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.restaurant enable row level security;
alter table public.products enable row level security;
