begin;

drop table if exists public.delivery_routes cascade;
drop table if exists public.order_items cascade;
drop table if exists public.orders cascade;
drop table if exists public.products cascade;
drop table if exists public.categories cascade;
drop table if exists public.user_has_roles cascade;
drop table if exists public.delivery cascade;
drop table if exists public.restaurant cascade;
drop table if exists public.client cascade;
drop table if exists public.login cascade;
drop table if exists public.roles cascade;
drop table if exists public.users cascade;

create table public.users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  rut text,
  name text,
  last_name text,
  phone text unique,
  photo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.login (
  id bigint generated by default as identity primary key,
  login text not null unique,
  password text not null,
  id_users bigint not null unique references public.users(id) on delete cascade,
  status integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  image text,
  route text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_has_roles (
  id bigint generated by default as identity primary key,
  id_user bigint not null references public.users(id) on delete cascade,
  id_rol bigint not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_user, id_rol)
);

create table public.client (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  end_date timestamptz
);

create table public.restaurant (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  name text not null,
  address text,
  created_at timestamptz not null default now()
);

create table public.delivery (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  vehicle text,
  created_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  image text,
  created_at timestamptz not null default now()
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete restrict,
  restaurant_id bigint not null references public.restaurant(id) on delete cascade,
  name text not null,
  description text,
  price numeric(12,2) not null check (price >= 0),
  image text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.orders (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.client(id) on delete restrict,
  restaurant_id bigint not null references public.restaurant(id) on delete restrict,
  delivery_id bigint references public.delivery(id) on delete set null,
  status text not null default 'Nuevo pedido',
  address text not null,
  subtotal numeric(12,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method text not null default 'Efectivo',
  created_at timestamptz not null default now()
);

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null,
  total numeric(12,2) not null
);

create table public.delivery_routes (
  id bigint generated by default as identity primary key,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  pickup_address text not null,
  delivery_address text not null,
  distance_km numeric(7,2) not null,
  estimated_minutes integer not null,
  status text not null,
  created_at timestamptz not null default now()
);

create index idx_login_user on public.login(id_users);
create index idx_user_has_roles_user on public.user_has_roles(id_user);
create index idx_user_has_roles_role on public.user_has_roles(id_rol);
create index idx_products_category on public.products(category_id);
create index idx_products_restaurant on public.products(restaurant_id);
create index idx_orders_client on public.orders(client_id);
create index idx_orders_restaurant on public.orders(restaurant_id);
create index idx_orders_delivery on public.orders(delivery_id);
create index idx_order_items_order on public.order_items(order_id);
create index idx_order_items_product on public.order_items(product_id);

insert into public.users (id,email,rut,name,last_name,phone,photo) values
  (1,'cliente@demo.cl','11.111.111-1','Cliente','Demo','+56911111111',null),
  (2,'restaurante@demo.cl','22.222.222-2','Restaurante','Demo','+56922222222',null),
  (3,'repartidor@demo.cl','33.333.333-3','Repartidor','Demo','+56933333333',null),
  (4,'admin@demo.cl','44.444.444-4','Admin','Multirol','+56944444444',null),
  (5,'araucomaipu@flashdrop.cl','55.555.555-5','Flash Bites','Arauco Maipu','+56955555555',null);

insert into public.login (id,login,password,id_users,status) values
  (1,'cliente@demo.cl','$2b$10$K0ZXwndhzN0H5uw6bfxF9eMqGEbiHunGMkv6/U9bE.BGr91d6tYM.',1,1),
  (2,'restaurante@demo.cl','$2b$10$K0ZXwndhzN0H5uw6bfxF9eMqGEbiHunGMkv6/U9bE.BGr91d6tYM.',2,1),
  (3,'repartidor@demo.cl','$2b$10$K0ZXwndhzN0H5uw6bfxF9eMqGEbiHunGMkv6/U9bE.BGr91d6tYM.',3,1),
  (4,'admin@demo.cl','$2b$10$K0ZXwndhzN0H5uw6bfxF9eMqGEbiHunGMkv6/U9bE.BGr91d6tYM.',4,1),
  (5,'araucomaipu@flashdrop.cl','$2b$10$K0ZXwndhzN0H5uw6bfxF9eMqGEbiHunGMkv6/U9bE.BGr91d6tYM.',5,1);

insert into public.roles (id,name,image,route) values
  (1,'Cliente','','/client/products/list'),
  (2,'Restaurante','','/restaurant/orders/list'),
  (3,'Repartidor','','/delivery/orders/list');

insert into public.user_has_roles (id,id_user,id_rol) values
  (1,1,1),(2,2,2),(3,3,3),(4,4,1),(5,4,2),(6,4,3),(7,5,2);

insert into public.client (id,user_id) values (1,1),(2,4);
insert into public.restaurant (id,user_id,name,address) values
  (1,2,'Urban Burger Demo','Av. Providencia 1200'),
  (2,4,'Flash Restaurant Demo','Los Leones 850'),
  (3,5,'Flash Bites Arauco Maipu','Av. Americo Vespucio 399, Maipu');
insert into public.delivery (id,user_id,vehicle) values (1,3,'Moto'),(2,4,'Auto');

insert into public.categories (id,name,description,image) values
  (1,'Hamburguesas','Combos y sandwiches preparados al momento','assets/img/burger1.png'),
  (2,'Pizzas','Pizzas familiares, medianas y porcionadas','assets/img/pizza.png'),
  (3,'Bebidas','Bebidas, jugos y aguas','assets/img/bag.png'),
  (4,'Promociones','Ofertas destacadas para delivery express','assets/img/hamburguesa.png');

insert into public.products (id,category_id,restaurant_id,name,description,price,image,is_available) values
  (1,1,1,'Burger doble','Doble carne, cheddar, pepinillos y salsa de la casa',8990,'assets/img/burger1.png',true),
  (2,1,1,'Burger crispy','Pollo crispy, lechuga, tomate y mayo ahumada',7490,'assets/img/burger2.png',true),
  (3,4,1,'Combo urbano','Burger doble, papas fritas y bebida lata',11990,'assets/img/hamburguesa.png',true),
  (4,2,2,'Pizza pepperoni','Pizza familiar con pepperoni y extra queso',11500,'assets/img/pizza.png',true),
  (5,2,2,'Pizza vegetariana','Champinones, aceitunas, pimenton y mozzarella',10900,'assets/img/pizza2.png',true),
  (6,3,2,'Bebida lata','Bebida individual 350cc',1490,'assets/img/bag.png',true),
  (7,4,2,'Pack familiar pizza','Pizza familiar, 2 bebidas y pan de ajo',15990,'assets/img/pizza.png',true),
  (8,1,1,'Cuarto de libra','queso y carne',9000,'https://img.asmedia.epimg.net/resizer/v2/FQLWD65HWNDKPHTIUK3IBKHFOM.png?auth=ad3df6cdb1bbf8b840447c8b2e4142364feed32d475a9e18cb91d0c11ba47a10&width=375',true),
  (9,3,2,'MCnico','asdasd',10000,null,true),
  (10,1,3,'Burger Arauco','Carne, queso cheddar, tomate y salsa de la casa',8990,'assets/img/burger1.png',true),
  (11,2,3,'Pizza Maipu familiar','Pepperoni, mozzarella y salsa de tomate',12990,'assets/img/pizza.png',true),
  (12,4,3,'Papas cheddar','Papas crujientes con cheddar y cebollin',4990,'assets/img/bag.png',true),
  (13,3,3,'Bebida 500 cc','Bebida individual fria',1990,'assets/img/bag.png',true);

insert into public.orders (id,client_id,restaurant_id,delivery_id,status,address,subtotal,delivery_fee,total,payment_method) values
  (1,1,1,1,'Preparando','Av. Providencia 1200, Santiago',19480,2500,21980,'Tarjeta'),
  (2,1,2,1,'Listo para retiro','Los Leones 850, Santiago',11500,2200,13700,'Efectivo'),
  (3,2,1,2,'En camino','Nueva Costanera 3900, Vitacura',11990,3000,14990,'Tarjeta'),
  (4,2,2,null,'Nuevo pedido','Manuel Montt 420, Providencia',17480,2500,19980,'Transferencia'),
  (5,1,1,1,'Entregado','Santa Isabel 060, Santiago',8990,2000,10990,'Tarjeta'),
  (6,1,2,1,'Nuevo pedido','Av. Providencia 1200, Santiago',15990,2500,18490,'Efectivo'),
  (7,1,1,1,'Nuevo pedido','Juan bohon 1622, Santiago',7490,2500,9990,'Efectivo'),
  (8,1,2,1,'Nuevo pedido','selene 1421, Santiago',10900,2500,13400,'Efectivo'),
  (9,1,1,1,'Nuevo pedido','selene 1422, Santiago',11990,2500,14490,'Efectivo'),
  (10,1,2,1,'Nuevo pedido','Av. Providencia 125, Santiago',10000,2500,12500,'Efectivo');

insert into public.order_items (id,order_id,product_id,quantity,unit_price,total) values
  (1,1,1,2,8990,17980),(2,1,6,1,1490,1490),(3,2,4,1,11500,11500),
  (4,3,3,1,11990,11990),(5,4,5,1,10900,10900),(6,4,6,2,1490,2980),
  (7,5,1,1,8990,8990),(8,6,7,1,15990,15990),(9,7,2,1,7490,7490),
  (10,8,5,1,10900,10900),(11,9,3,1,11990,11990),(12,10,9,1,10000,10000);

insert into public.delivery_routes (id,order_id,pickup_address,delivery_address,distance_km,estimated_minutes,status) values
  (1,1,'Urban Burger Demo, Av. Providencia 1000','Av. Providencia 1200, Santiago',2.4,18,'Retirar pedido'),
  (2,2,'Flash Restaurant Demo, Los Leones 500','Los Leones 850, Santiago',4.1,25,'Listo para retiro'),
  (3,3,'Urban Burger Demo, Av. Providencia 1000','Nueva Costanera 3900, Vitacura',6.8,32,'En camino'),
  (4,5,'Urban Burger Demo, Av. Providencia 1000','Santa Isabel 060, Santiago',1.8,12,'Entregado'),
  (5,6,'Los Leones 850','Av. Providencia 1200, Santiago',3.2,20,'Pendiente'),
  (6,7,'Av. Providencia 1200','Juan bohon 1622, Santiago',3.2,20,'Pendiente'),
  (7,8,'Los Leones 850','selene 1421, Santiago',3.2,20,'Pendiente'),
  (8,9,'Av. Providencia 1200','selene 1422, Santiago',3.2,20,'Pendiente'),
  (9,10,'Los Leones 850','Av. Providencia 125, Santiago',3.2,20,'Pendiente');

select setval(pg_get_serial_sequence('public.users','id'),5,true);
select setval(pg_get_serial_sequence('public.login','id'),5,true);
select setval(pg_get_serial_sequence('public.roles','id'),3,true);
select setval(pg_get_serial_sequence('public.user_has_roles','id'),7,true);
select setval(pg_get_serial_sequence('public.client','id'),2,true);
select setval(pg_get_serial_sequence('public.restaurant','id'),3,true);
select setval(pg_get_serial_sequence('public.delivery','id'),2,true);
select setval(pg_get_serial_sequence('public.categories','id'),4,true);
select setval(pg_get_serial_sequence('public.products','id'),13,true);
select setval(pg_get_serial_sequence('public.orders','id'),10,true);
select setval(pg_get_serial_sequence('public.order_items','id'),12,true);
select setval(pg_get_serial_sequence('public.delivery_routes','id'),9,true);

alter table public.users enable row level security;
alter table public.login enable row level security;
alter table public.roles enable row level security;
alter table public.user_has_roles enable row level security;
alter table public.client enable row level security;
alter table public.restaurant enable row level security;
alter table public.delivery enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.delivery_routes enable row level security;

insert into storage.buckets (id,name,public)
values ('fotos_delivery','fotos_delivery',true)
on conflict (id) do update set public = true;

commit;
