-- =====================================================================
-- V1 - Esquema propietario de auth-service
--
-- Cinco tablas y nada mas: users, login, roles, user_has_roles y
-- refresh_tokens. Ninguna tabla de otro microservicio vive aca (regla de
-- propiedad de datos). Las referencias a usuarios desde Catalog, Orders o
-- Delivery son identificadores logicos, no claves foraneas entre bases.
--
-- Este DDL es el mismo que se valido contra un PostgreSQL real el
-- 24/08/2026, sin los `drop table` (Flyway versiona, no reaplica) ni las
-- sentencias de Row Level Security, que existian porque PostgREST exponia
-- la base a la red. Con Floci RDS la base solo la alcanza el servicio por
-- JDBC.
-- =====================================================================

-- =====================================================================
-- auth-service — esquema independiente
-- MIGRATION_PLAN.pdf §4.1: "Crear esquema SQL independiente con las tablas:
-- users, login, roles, user_has_roles, refresh_tokens."
--
-- Este esquema vive en el proyecto Supabase EXCLUSIVO de auth-service.
-- Ninguna otra tabla del sistema (client, restaurant, delivery, orders...)
-- pertenece aquí: los demás servicios consultan por HTTP a /api/internal/**.
--
-- Aplicar con:  psql "$AUTH_DB_URL" -f 01_schema.sql
--          o:  Supabase Studio → SQL Editor → pegar y ejecutar
--
-- Idempotente: se puede re-ejecutar sobre una base ya creada.
-- =====================================================================

-- Orden inverso a las dependencias para que los drops no fallen.

-- ---------------------------------------------------------------------
-- users — identidad y datos de perfil
-- Contrato expuesto en GET /api/internal/users/{id} (PDF §9.1):
--   { id, name, lastName, email, phone }
-- ---------------------------------------------------------------------
create table public.users (
  id         bigint generated by default as identity primary key,
  email      text        not null unique,
  rut        text,
  name       text,
  last_name  text,
  phone      text unique,
  photo      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table public.users is
  'Identidad de usuario. Dueño: auth-service. Los demás servicios la leen vía GET /api/internal/users/{id}.';

-- ---------------------------------------------------------------------
-- login — credenciales. Separada de users para que un SELECT de perfil
-- nunca arrastre el hash de contraseña.
-- ---------------------------------------------------------------------
create table public.login (
  id         bigint generated by default as identity primary key,
  login      text        not null unique,
  password   text        not null,          -- bcrypt, nunca texto plano
  id_users   bigint      not null unique references public.users(id) on delete cascade,
  status     integer     not null default 1, -- 1 = ACTIVE, 0 = INACTIVE
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- roles / user_has_roles — relación N:M
-- ---------------------------------------------------------------------
create table public.roles (
  id         bigint generated by default as identity primary key,
  name       text        not null unique,
  image      text,
  route      text        not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.user_has_roles (
  id         bigint generated by default as identity primary key,
  id_user    bigint      not null references public.users(id) on delete cascade,
  id_rol     bigint      not null references public.roles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id_user, id_rol)
);

-- ---------------------------------------------------------------------
-- refresh_tokens — tabla nueva creada por auth (PDF §1)
--
-- Se guarda SOLO el hash SHA-256 del token opaco; el valor crudo jamás
-- toca la base. `id` es `generated by default` a propósito: el cliente
-- (RefreshTokenManager) provee un id aleatorio, pero un INSERT manual
-- desde SQL puede omitirlo y dejar que la identidad lo genere.
-- ---------------------------------------------------------------------
create table public.refresh_tokens (
  id         bigint generated by default as identity primary key,
  user_id    bigint      not null references public.users(id) on delete cascade,
  token_hash text        not null unique,
  expires_at timestamptz not null,
  revoked    boolean     not null default false,
  created_at timestamptz not null default now()
);

-- Índices de los accesos reales del servicio.
create index idx_users_email             on public.users (email);
create index idx_login_login             on public.login (login);
create index idx_user_has_roles_user     on public.user_has_roles (id_user);
create index idx_refresh_tokens_user     on public.refresh_tokens (user_id);
create index idx_refresh_tokens_activos  on public.refresh_tokens (user_id) where revoked = false;
